name: taska-manager

services:
  application:
    build:
      context: ./../../
      dockerfile: ./docker/production/dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - taska-network
